# Generated by Django 5.2 on 2025-11-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_publications',
            field=models.IntegerField(default=0),
        ),
    ]
