# Generated by Django 5.2 on 2025-11-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0002_user_num_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
