# Generated by Django 5.2 on 2025-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0003_petphoto_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
